
STRINGS.TOO_MANY_ITEMS.UI.BUTTON.HEALTH = "生命 100%"
STRINGS.TOO_MANY_ITEMS.UI.BUTTON.SANITY = "脑残 100%"
STRINGS.TOO_MANY_ITEMS.UI.BUTTON.HUNGER = "饱食 100%"
STRINGS.TOO_MANY_ITEMS.UI.BUTTON.WET = "湿度 0%"
STRINGS.TOO_MANY_ITEMS.UI.BUTTON.TEMPERATURE = "温度: 20\176C"
STRINGS.TOO_MANY_ITEMS.UI.BUTTON.LOGMETER = "木头计数 100%"

STRINGS.TOO_MANY_ITEMS.UI.BUTTON.GODMODE = "上帝模式(开/关)"
STRINGS.TOO_MANY_ITEMS.UI.BUTTON.CREATIVEMODE = "创造模式(开/关)"
STRINGS.TOO_MANY_ITEMS.UI.BUTTON.DEBUGMENU = "调试菜单(开/关)"
STRINGS.TOO_MANY_ITEMS.UI.BUTTON.EMPTYBACKPACK = "清空背包"


STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SEASON.SPRINGTIP = "春天来了!"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SEASON.SUMMERTIP = "夏天来了!"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SEASON.AUTUMNTIP = "秋天来了!"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SEASON.WINTERTIP = "冬天来了!"


STRINGS.TOO_MANY_ITEMS.UI.DEBUG.TIME.TEXT = "时间:"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.TIME.NEXT = "下"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.TIME.NEXTTIP = "下一时段"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.TIME.ODAY = "1天"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.TIME.ODAYTIP = "跳过1天"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.TIME.FDAYS = "5天"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.TIME.FDAYSTIP = "跳过5天"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.TIME.TDAYS = "10天"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.TIME.TDAYSTIP = "跳过10天"


STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SPEED.TEXT = "速度:"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SPEED.SLOW = "慢"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SPEED.SLOWTIP = "60%速度"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SPEED.NORMAL = "正常"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SPEED.NORMALTIP = "100%速度"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SPEED.FAST = "快"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SPEED.FASTTIP = "200%速度"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SPEED.FLY = "飞"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SPEED.FLYTIP = "400%速度"


STRINGS.TOO_MANY_ITEMS.UI.DEBUG.WEATHER.TEXT = "天气:"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.WEATHER.LIGHTNINGTIP = "让闪电劈死我吧"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.WEATHER.WATER = ".,;:':;,."
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.WEATHER.WATERTIP = "下雨/下雪"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.WEATHER.NOWATER = ",.'o'.,"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.WEATHER.NOWATERTIP = "停止下雨/下雪"


STRINGS.TOO_MANY_ITEMS.UI.DEBUG.CHARACTER.TEXT = "角色:"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.CHARACTER.KILL = "自杀"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.CHARACTER.KILLTIP = "不想活了"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.CHARACTERREBIRTH = "重生"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.CHARACTER.REBIRTHTIP = "鬼魂重生"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.CHARACTER.DESPAWN = "重选"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.CHARACTER.DESPAWNTIP = "重选角色"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.CHARACTER.GATHER = "集合"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.CHARACTER.GATHERTIP = "把所有人召集起来!"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.CHARACTER.UNLOCKTECH = "解锁"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.CHARACTER.UNLOCKTECHTIP = "解锁科技树"


STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SERVER.TEXT = "服务器:"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SERVER.RESET = "重置"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SERVER.RESETTIP = "将世界重置"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SERVER.REGENERATE = "再生"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SERVER.REGENERATETIP = "让世界再生"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SERVER.ROLLBACK = "回档"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SERVER.ROLLBACKTIP = "返回到上次存档状态"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SERVER.SAVE = "保存"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SERVER.SAVETIP = "保存当前世界"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SERVER.SHUTDOWN = "关闭"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SERVER.SHUTDOWNTIP = "关闭服务器"


STRINGS.TOO_MANY_ITEMS.UI.SIDEBAR.A = "全\n部"
STRINGS.TOO_MANY_ITEMS.UI.SIDEBAR.TIPA = "显示所有道具"

STRINGS.TOO_MANY_ITEMS.UI.SIDEBAR.F = "食\n物"
STRINGS.TOO_MANY_ITEMS.UI.SIDEBAR.TIPF = "显示所有食物"

STRINGS.TOO_MANY_ITEMS.UI.SIDEBAR.R = "材\n料"
STRINGS.TOO_MANY_ITEMS.UI.SIDEBAR.TIPR = "显示所有材料"

STRINGS.TOO_MANY_ITEMS.UI.SIDEBAR.W = "武\n器"
STRINGS.TOO_MANY_ITEMS.UI.SIDEBAR.TIPW = "显示所有武器"

STRINGS.TOO_MANY_ITEMS.UI.SIDEBAR.T = "工\n具"
STRINGS.TOO_MANY_ITEMS.UI.SIDEBAR.TIPT = "显示所有工具"

STRINGS.TOO_MANY_ITEMS.UI.SIDEBAR.C = "衣\n服"
STRINGS.TOO_MANY_ITEMS.UI.SIDEBAR.TIPC= "显示所有衣服"

STRINGS.TOO_MANY_ITEMS.UI.SIDEBAR.G = "礼\n物"
STRINGS.TOO_MANY_ITEMS.UI.SIDEBAR.TIPG= "显示所有礼物"

STRINGS.TOO_MANY_ITEMS.UI.SIDEBAR.O = "其\n它"
STRINGS.TOO_MANY_ITEMS.UI.SIDEBAR.TIPO = "显示其它道具(某些道具可能引起崩溃)"


STRINGS.TOO_MANY_ITEMS.UI.SEARCHBAR.TEXT = "搜索你想要的道具"
STRINGS.TOO_MANY_ITEMS.UI.SEARCHBAR.TIP = "点击输入文本!"
STRINGS.TOO_MANY_ITEMS.UI.SEARCH.TEXT= "搜索"
STRINGS.TOO_MANY_ITEMS.UI.SEARCH.TIP = "点击搜索!"

