GLOBAL.TUNING.AXE_USES = 1000
GLOBAL.TUNING.HAMMER_USES = 750
GLOBAL.TUNING.SHOVEL_USES = 250
GLOBAL.TUNING.PITCHFORK_USES = 250
GLOBAL.TUNING.PICKAXE_USES = 330
GLOBAL.TUNING.BUGNET_USES = 100
GLOBAL.TUNING.FISHINGROD_USES = 90
