--[[
	--- This is Wilson's speech file for Don't Starve Together ---
	Write your character's lines here. If you want to use another speech file as a base, get them from data\scripts\
	
	If you have the DLC and want custom lines for those, use a speech file from data\DLC0001\scripts instead.
	
	If you want to use quotation marks in a quote, put a \ before it.
	Example:
	"Like \"this\"."
]]
return {
	ACTIONFAIL =
	{
		SHAVE =
		{
			AWAKEBEEFALO = "... ... ...",
			GENERIC = "... ... ...",
			NOBITS = "... ... ...",
		},
		STORE =
		{
			GENERIC = "... ... ...",
			NOTALLOWED = "... ... ...",
			INUSE = "... ... ...",
		},
		RUMMAGE =
		{	
			GENERIC = "... ... ...",
			INUSE = "... ... ...",	
		},
	},
	ACTIONFAIL_GENERIC = "... ... ...",
	ANNOUNCE_ADVENTUREFAIL = "... ... ...",
	ANNOUNCE_BEES = "... ... ...",
	ANNOUNCE_BOOMERANG = "... ... ...",
	ANNOUNCE_CHARLIE = "... ... ...",
	ANNOUNCE_CHARLIE_ATTACK = "... ... ...",
	ANNOUNCE_COLD = "... ... ...",
	ANNOUNCE_CRAFTING_FAIL = "... ... ...",
	ANNOUNCE_DEERCLOPS = "... ... ...",
	ANNOUNCE_DUSK = "... ... ...",
	ANNOUNCE_EAT =
	{
		GENERIC = "... ... ...",
		PAINFUL = "... ... ...",
		SPOILED = "... ... ...",
		STALE = "... ... ...",
	},
	ANNOUNCE_ENTER_DARK = "... ... ...",
	ANNOUNCE_ENTER_LIGHT = "... ... ...",
	ANNOUNCE_FREEDOM = "... ... ...",
	ANNOUNCE_HIGHRESEARCH = "... ... ...",
	ANNOUNCE_HOUNDS = "... ... ...",
	ANNOUNCE_HUNGRY = "... ... ...",
	ANNOUNCE_HUNT_BEAST_NEARBY = "... ... ...",
	ANNOUNCE_HUNT_LOST_TRAIL = "... ... ...",
	ANNOUNCE_INV_FULL = "... ... ...",
	ANNOUNCE_KNOCKEDOUT = "... ... ...",
	ANNOUNCE_LOWRESEARCH = "... ... ...",
	ANNOUNCE_MOSQUITOS = "... ... ...",
	ANNOUNCE_NODANGERSLEEP = "... ... ...",
	ANNOUNCE_NODAYSLEEP = "... ... ...",
	ANNOUNCE_NODAYSLEEP_CAVE = "... ... ...",
	ANNOUNCE_NOHUNGERSLEEP = "... ... ...",
	ANNOUNCE_NODANGERAFK = "... ... ...",
	ANNOUNCE_NO_TRAP = "... ... ...",
	ANNOUNCE_PECKED = "... ... ...",
	ANNOUNCE_QUAKE = "... ... ...",
	ANNOUNCE_RESEARCH = "... ... ...",
	ANNOUNCE_THORNS = "... ... ...",
	ANNOUNCE_TORCH_OUT = "... ... ...",
	ANNOUNCE_TRAP_WENT_OFF = "... ... ...",
	ANNOUNCE_UNIMPLEMENTED = "... ... ...",
	ANNOUNCE_WORMHOLE = "... ... ...",
	ANNOUNCE_CANFIX = "\n... ... ...",
	ANNOUNCE_ACCOMPLISHMENT = "... ... ...",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "... ... ...",	
	ANNOUNCE_BECOMEGHOST = "... ... ...",
	ANNOUNCE_GHOSTDRAIN = "... ... ...",

	DESCRIBE_SAMECHARACTER = "... ... ...",
	
	BATTLECRY =
	{
		GENERIC = "... ... ...",
		PIG = "... ... ...",
		PREY = "... ... ...",
		SPIDER = "... ... ...",
		SPIDER_WARRIOR = "... ... ...",
	},
	COMBAT_QUIT =
	{
		GENERIC = "... ... ...",
		PIG = "... ... ...",
		PREY = "... ... ...",
		SPIDER = "... ... ...",
		SPIDER_WARRIOR = "... ... ...",
	},
	DESCRIBE =
	{
        PLAYER =
        {
            GENERIC = "... ... ...",
            ATTACKER = "... ... ...",
            MURDERER = "... ... ...",
            REVIVER = "... ... ...",
            GHOST = "... ... ...",
        },
		WILSON = 
		{
			GENERIC = "... ... ...",
			ATTACKER = "... ... ...",
			MURDERER = "... ... ...",
			REVIVER = "... ... ...",
			GHOST = "... ... ...",
		},
		WOLFGANG = 
		{
			GENERIC = "... ... ...",
			ATTACKER = "... ... ...",
			MURDERER = "... ... ...",
			REVIVER = "... ... ...",
			GHOST = "... ... ...",
		},
		WAXWELL = 
		{
			GENERIC = "... ... ...",
			ATTACKER = "... ... ...",
			MURDERER = "... ... ...",
			REVIVER = "... ... ...",
			GHOST = "... ... ...",
		},
		WX78 = 
		{
			GENERIC = "... ... ...",
			ATTACKER = "... ... ...",
			MURDERER = "... ... ...",
			REVIVER = "... ... ...",
			GHOST = "... ... ...",
		},
		WILLOW = 
		{
			GENERIC = "... ... ...",
			ATTACKER = "... ... ...",
			MURDERER = "... ... ...",
			REVIVER = "... ... ...",
			GHOST = "... ... ...",
		},
		WENDY = 
		{
			GENERIC = "... ... ...",
			ATTACKER = "... ... ...",
			MURDERER = "... ... ...",
			REVIVER = "... ... ...",
			GHOST = "... ... ...",
		},
		WOODIE = 
		{
			GENERIC = "... ... ...",
			ATTACKER = "... ... ...",
			MURDERER = "... ... ...",
			REVIVER = "... ... ...",
			GHOST = "... ... ...",
		},
		WICKERBOTTOM = 
		{
			GENERIC = "... ... ...",
			ATTACKER = "... ... ...",
			MURDERER = "... ... ...",
			REVIVER = "... ... ...",
			GHOST = "... ... ...",
		},
		WES = 
		{
			GENERIC = "... ... ...",
			ATTACKER = "... ... ...",
			MURDERER = "... ... ...",
			REVIVER = "... ... ...",
			GHOST = "... ... ...",
		},
		MULTIPLAYER_PORTAL = "... ... ...",
		WORMLIGHT = "... ... ...",
		WORM =
		{
		    PLANT = "... ... ...",
		    DIRT = "... ... ...",
		    WORM = "... ... ...",
		},
		MOLE =
		{
			HELD = "... ... ...",
			UNDERGROUND = "... ... ...",
			ABOVEGROUND = "... ... ...",
		},
		MOLEHILL = "... ... ...",
		MOLEHAT = "... ... ...",

		EEL = "... ... ...",
		EEL_COOKED = "... ... ...",
		UNAGI = "... ... ...",
		EYETURRET = "... ... ...",
		EYETURRET_ITEM = "... ... ...",
		MINOTAURHORN = "... ... ...",
		MINOTAURCHEST = "... ... ...",
		THULECITE_PIECES = "... ... ...",
		POND_ALGAE = "... ... ...",
		GREENSTAFF = "... ... ...",
		POTTEDFERN = "... ... ...",

		THULECITE = "... ... ...",
		ARMORRUINS = "... ... ...",
		RUINS_BAT = "... ... ...",
		RUINSHAT = "... ... ...",
		NIGHTMARE_TIMEPIECE =
		{
		CALM = "... ... ...",
		WARN = "... ... ...",
		WAXING = "... ... ...",
		STEADY = "... ... ...",
		WANING = "... ... ...",
		DAWN = "... ... ...",
		NOMAGIC = "... ... ...",
		},
		BISHOP_NIGHTMARE = "... ... ...",
		ROOK_NIGHTMARE = "... ... ...",
		KNIGHT_NIGHTMARE = "... ... ...",
		MINOTAUR = "... ... ...",
		SPIDER_DROPPER = "... ... ...",
		NIGHTMARELIGHT = "... ... ...",
		GREENGEM = "... ... ...",
		RELIC = "... ... ...",
		RUINS_RUBBLE = "... ... ...",
		MULTITOOL_AXE_PICKAXE = "... ... ...",
		ORANGESTAFF = "... ... ...",
		YELLOWAMULET = "... ... ...",
		GREENAMULET = "... ... ...",
		SLURPERPELT = "... ... ...",	

		SLURPER = "... ... ...",
		SLURPER_PELT = "... ... ...",
		ARMORSLURPER = "... ... ...",
		ORANGEAMULET = "... ... ...",
		YELLOWSTAFF = "... ... ...",
		YELLOWGEM = "... ... ...",
		ORANGEGEM = "... ... ...",
		TELEBASE = 
		{
			VALID = "... ... ...",
			GEMS = "... ... ...",
		},
		GEMSOCKET = 
		{
			VALID = "... ... ...",
			GEMS = "... ... ...",
		},
		STAFFLIGHT = "... ... ...",
		RESEARCHLAB4 = "... ... ...",
	
        ANCIENT_ALTAR = "... ... ...",

        ANCIENT_ALTAR_BROKEN = "... ... ...",

        ANCIENT_STATUE = "... ... ...",

        LICHEN = "... ... ...",
		CUTLICHEN = "... ... ...",

		CAVE_BANANA = "... ... ...",
		CAVE_BANANA_COOKED = "... ... ...",
		CAVE_BANANA_TREE = "... ... ...",
		ROCKY = "... ... ...",
		
		COMPASS =
		{
			GENERIC="... ... ...",
			N = "... ... ...",
			S = "... ... ...",
			E = "... ... ...",
			W = "... ... ...",
			NE = "... ... ...",
			SE = "... ... ...",
			NW = "... ... ...",
			SW = "... ... ...",
		},

		NIGHTMARE_TIMEPIECE =
		{
			WAXING = "... ... ...",
			STEADY = "... ... ...",
			WANING = "... ... ...",
			DAWN = "... ... ...",
			WARN = "... ... ...",
			CALM = "... ... ...",
			NOMAGIC = "... ... ...",
		},

		HOUNDSTOOTH="... ... ...",
		ARMORSNURTLESHELL="... ... ...",
		BAT="... ... ...",
		BATBAT = "... ... ...",
		BATWING="... ... ...",
		BATWING_COOKED="... ... ...",
		BEDROLL_FURRY="... ... ...",
		BUNNYMAN="... ... ...",
		FLOWER_CAVE="... ... ...",
		FLOWER_CAVE_DOUBLE="... ... ...",
		FLOWER_CAVE_TRIPLE="... ... ...",
		GUANO="... ... ...",
		LANTERN="... ... ...",
		LIGHTBULB="... ... ...",
		MANRABBIT_TAIL="... ... ...",
		MUSHTREE_TALL  ="... ... ...",
		MUSHTREE_MEDIUM="... ... ...",
		MUSHTREE_SMALL ="... ... ...",
		RABBITHOUSE="... ... ...",
		SLURTLE="... ... ...",
		SLURTLE_SHELLPIECES="... ... ...",
		SLURTLEHAT="... ... ...",
		SLURTLEHOLE="... ... ...",
		SLURTLESLIME="... ... ...",
		SNURTLE="... ... ...",
		SPIDER_HIDER="... ... ...",
		SPIDER_SPITTER="... ... ...",
		SPIDERHOLE="... ... ...",
		STALAGMITE="... ... ...",
		STALAGMITE_FULL="... ... ...",
		STALAGMITE_LOW="... ... ...",
		STALAGMITE_MED="... ... ...",
		STALAGMITE_TALL="... ... ...",
		STALAGMITE_TALL_FULL="... ... ...",
		STALAGMITE_TALL_LOW="... ... ...",
		STALAGMITE_TALL_MED="... ... ...",

		TURF_CARPETFLOOR = "... ... ...",
		TURF_CHECKERFLOOR = "... ... ...",
		TURF_DIRT = "... ... ...",
		TURF_FOREST = "... ... ...",
		TURF_GRASS = "... ... ...",
		TURF_MARSH = "... ... ...",
		TURF_ROAD = "... ... ...",
		TURF_ROCKY = "... ... ...",
		TURF_SAVANNA = "... ... ...",
		TURF_WOODFLOOR = "... ... ...",

		TURF_CAVE="... ... ...",
		TURF_FUNGUS="... ... ...",
		TURF_SINKHOLE="... ... ...",
		TURF_UNDERROCK="... ... ...",
		TURF_MUD="... ... ...",

		POWCAKE = "... ... ...",
        CAVE_ENTRANCE = 
        {
            GENERIC="... ... ...",
            OPEN = "... ... ...",
        },
        CAVE_EXIT = "... ... ...",
		MAXWELLPHONOGRAPH = "... ... ...",
		BOOMERANG = "... ... ...",
		PIGGUARD = "... ... ...",
		ABIGAIL = "... ... ...",
		ADVENTURE_PORTAL = "... ... ...",
		AMULET = "... ... ...",
		ANIMAL_TRACK = "... ... ...",
		ARMORGRASS = "... ... ...",
		ARMORMARBLE = "... ... ...",
		ARMORWOOD = "... ... ...",
		ARMOR_SANITY = "... ... ...",
		ASH =
		{
			GENERIC = "... ... ...",
			REMAINS_EYE_BONE = "... ... ...",
			REMAINS_THINGIE = "... ... ...",
		},
		AXE = "... ... ...",
		BABYBEEFALO = "... ... ...",
		BACKPACK = "... ... ...",
		BACONEGGS = "... ... ...",
		BANDAGE = "... ... ...",
		BASALT = "... ... ...",
		BATBAT = "... ... ...",
		BEARDHAIR = "... ... ...",
		BEDROLL_STRAW = "... ... ...",
		BEE =
		{
			GENERIC = "... ... ...",
			HELD = "... ... ...",
		},
		BEEBOX =
		{
			FULLHONEY = "... ... ...",
			GENERIC = "... ... ...",
			NOHONEY = "... ... ...",
			SOMEHONEY = "... ... ...",
		},
		BEEFALO =
		{
			FOLLOWER = "... ... ...",
			GENERIC = "... ... ...",
			NAKED = "... ... ...",
			SLEEPING = "... ... ...",
		},
		BEEFALOHAT = "... ... ...",
		BEEFALOWOOL = "... ... ...",
		BEEHAT = "... ... ...",
		BEEHIVE = "... ... ...",
		BEEMINE = "... ... ...",
		BEEMINE_MAXWELL = "... ... ...",
		BERRIES = "... ... ...",
		BERRIES_COOKED = "... ... ...",
		BERRYBUSH =
		{
			BARREN = "... ... ...",
			GENERIC = "... ... ...",
			PICKED = "... ... ...",
		},
		BIRDCAGE =
		{
			GENERIC = "... ... ...",
			OCCUPIED = "... ... ...",
			SLEEPING = "... ... ...",
		},
		BIRDTRAP = "... ... ...",
		BIRD_EGG = "... ... ...",
		BIRD_EGG_COOKED = "... ... ...",
		BISHOP = "... ... ...",
		BLOWDART_FIRE = "... ... ...",
		BLOWDART_SLEEP = "... ... ...",
		BLOWDART_PIPE = "... ... ...",
		BLUEAMULET = "... ... ...",
		BLUEGEM = "... ... ...",
		BLUEPRINT = "... ... ...",
		BLUE_CAP = "... ... ...",
		BLUE_CAP_COOKED = "... ... ...",
		BLUE_MUSHROOM =
		{
			GENERIC = "... ... ...",
			INGROUND = "... ... ...",
			PICKED = "... ... ...",
		},
		BOARDS = "... ... ...",
		BOAT = "... ... ...",
		BONESTEW = "... ... ...",
		BUGNET = "... ... ...",
		BUSHHAT = "... ... ...",
		BUTTER = "... ... ...",
		BUTTERFLY =
		{
			GENERIC = "... ... ...",
			HELD = "... ... ...",
		},
		BUTTERFLYMUFFIN = "... ... ...",
		BUTTERFLYWINGS = "... ... ...",
		CAMPFIRE =
		{
			EMBERS = "... ... ...",
			GENERIC = "... ... ...",
			HIGH = "... ... ...",
			LOW = "... ... ...",
			NORMAL = "... ... ...",
			OUT = "... ... ...",
		},
		CANE = "... ... ...",
		CARROT = "... ... ...",
		CARROT_COOKED = "... ... ...",
		CARROT_PLANTED = "... ... ...",
		CARROT_SEEDS = "... ... ...",
		CAVE_FERN = "... ... ...",
		CHARCOAL = "... ... ...",
        CHESSJUNK1 = "... ... ...",
        CHESSJUNK2 = "... ... ...",
        CHESSJUNK3 = "... ... ...",
		CHESTER = "... ... ...",
		CHESTER_EYEBONE =
		{
			GENERIC = "... ... ...",
			WAITING = "... ... ...",
		},
		COOKEDMANDRAKE = "... ... ...",
		COOKEDMEAT = "... ... ...",
		COOKEDMONSTERMEAT = "... ... ...",
		COOKEDSMALLMEAT = "... ... ...",
		COOKPOT =
		{
			COOKING_LONG = "... ... ...",
			COOKING_SHORT = "... ... ...",
			DONE = "... ... ...",
			EMPTY = "... ... ...",
		},
		CORN = "... ... ...",
		CORN_COOKED = "... ... ...",
		CORN_SEEDS = "... ... ...",
		CROW =
		{
			GENERIC = "... ... ...",
			HELD = "... ... ...",
		},
		CUTGRASS = "... ... ...",
		CUTREEDS = "... ... ...",
		CUTSTONE = "... ... ...",
		DEADLYFEAST = "... ... ...",
		DEERCLOPS = "... ... ...",
		DEERCLOPS_EYEBALL = "... ... ...",
		DEPLETED_GRASS =
		{
			GENERIC = "... ... ...",
		},
		DEVTOOL = "... ... ...",
		DEVTOOL_NODEV = "... ... ...",
		DIRTPILE = "... ... ...",
		DIVININGROD =
		{
			COLD = "... ... ...",
			GENERIC = "... ... ...",
			HOT = "... ... ...",
			WARM = "... ... ...",
			WARMER = "... ... ...",
		},
		DIVININGRODBASE =
		{
			GENERIC = "... ... ...",
			READY = "... ... ...",
			UNLOCKED = "... ... ...",
		},
		DIVININGRODSTART = "... ... ...",
		DRAGONFRUIT = "... ... ...",
		DRAGONFRUIT_COOKED = "... ... ...",
		DRAGONFRUIT_SEEDS = "... ... ...",
		DRAGONPIE = "... ... ...",
		DRUMSTICK = "... ... ...",
		DRUMSTICK_COOKED = "... ... ...",
		DUG_BERRYBUSH = "... ... ...",
		DUG_GRASS = "... ... ...",
		DUG_MARSH_BUSH = "... ... ...",
		DUG_SAPLING = "... ... ...",
		DURIAN = "... ... ...",
		DURIAN_COOKED = "... ... ...",
		DURIAN_SEEDS = "... ... ...",
		EARMUFFSHAT = "... ... ...",
		EGGPLANT = "... ... ...",
		EGGPLANT_COOKED = "... ... ...",
		EGGPLANT_SEEDS = "... ... ...",
		DECIDUOUSTREE = 
		{
			BURNING = "... ... ...",
			BURNT = "... ... ...",
			CHOPPED = "... ... ...",
			POISON = "... ... ...",
			GENERIC = "... ... ...",
		},
		ACORN = 
		{
		    GENERIC = "... ... ...",
		    PLANTED = "... ... ...",
		},
		ACORN_COOKED = "... ... ...",
		BIRCHNUTDRAKE = "... ... ...",
		EVERGREEN =
		{
			BURNING = "... ... ...",
			BURNT = "... ... ...",
			CHOPPED = "... ... ...",
			GENERIC = "... ... ...",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "... ... ...",
			BURNT = "... ... ...",
			CHOPPED = "... ... ...",
			GENERIC = "... ... ...",
		},
		EYEPLANT = "... ... ...",
		FARMPLOT =
		{
			GENERIC = "... ... ...",
			GROWING = "... ... ...",
			NEEDSFERTILIZER = "... ... ...",
		},
		FEATHERHAT = "... ... ...",
		FEATHER_CROW = "... ... ...",
		FEATHER_ROBIN = "... ... ...",
		FEATHER_ROBIN_WINTER = "... ... ...",
		FEM_PUPPET = "... ... ...",
		FIREFLIES =
		{
			GENERIC = "... ... ...",
			HELD = "... ... ...",
		},
		FIREHOUND = "... ... ...",
		FIREPIT =
		{
			EMBERS = "... ... ...",
			GENERIC = "... ... ...",
			HIGH = "... ... ...",
			LOW = "... ... ...",
			NORMAL = "... ... ...",
			OUT = "... ... ...",
		},
		FIRESTAFF = "... ... ...",

		FISH = "... ... ...",
		FISHINGROD = "... ... ...",
		FISHSTICKS = "... ... ...",
		FISHTACOS = "... ... ...",
		FISH_COOKED = "... ... ...",
		FLINT = "... ... ...",
		FLOWER = "... ... ...",
		FLOWERHAT = "... ... ...",
		FLOWER_EVIL = "... ... ...",
		FOLIAGE = "... ... ...",
		FOOTBALLHAT = "... ... ...",
		FROG =
		{
			DEAD = "... ... ...",
			GENERIC = "... ... ...",
			SLEEPING = "... ... ...",
		},
		FROGGLEBUNWICH = "... ... ...",
		FROGLEGS = "... ... ...",
		FROGLEGS_COOKED = "... ... ...",
		FRUITMEDLEY = "... ... ...",
		GEARS = "... ... ...",
		GHOST = "... ... ...",
		GOLDENAXE = "... ... ...",
		GOLDENPICKAXE = "... ... ...",
		GOLDENPITCHFORK = "... ... ...",
		GOLDENSHOVEL = "... ... ...",
		GOLDNUGGET = "... ... ...",
		GRASS =
		{
			BARREN = "... ... ...",
			BURNING = "... ... ...",
			GENERIC = "... ... ...",
			PICKED = "... ... ...",
		},
		GREEN_CAP = "... ... ...",
		GREEN_CAP_COOKED = "... ... ...",
		GREEN_MUSHROOM =
		{
			GENERIC = "... ... ...",
			INGROUND = "... ... ...",
			PICKED = "... ... ...",
		},
		GUNPOWDER = "... ... ...",
		HAMBAT = "... ... ...",
		HAMMER = "... ... ...",
		HEALINGSALVE = "... ... ...",
		HEATROCK =
		{
			COLD = "... ... ...",
			GENERIC = "... ... ...",
			HOT = "... ... ...",
			WARM = "... ... ...",
		},
		HOME = "... ... ...",
		HOMESIGN = "... ... ...",
		HONEY = "... ... ...",
		HONEYCOMB = "... ... ...",
		HONEYHAM = "... ... ...",
		HONEYNUGGETS = "... ... ...",
		HORN = "... ... ...",
		HOUND = "... ... ...!",
		HOUNDBONE = "... ... ...",
		HOUNDMOUND = "... ... ...",
		ICEBOX = "... ... ...",
		ICEHOUND = "... ... ...",
		INSANITYROCK =
		{
			ACTIVE = "... ... ...",
			INACTIVE = "... ... ...",
		},
		JAMMYPRESERVES = "... ... ...",
		KABOBS = "... ... ...",
		KILLERBEE =
		{
			GENERIC = "... ... ...",
			HELD = "... ... ...",
		},
		KNIGHT = "... ... ...",
		KOALEFANT_SUMMER = "... ... ...",
		KOALEFANT_WINTER = "... ... ...",
		KRAMPUS = "... ... ...",
		KRAMPUS_SACK = "... ... ...",
		LEIF = "... ... ...",
		LEIF_SPARSE = "... ... ...",
		LIGHTNING_ROD =
		{
			CHARGED = "... ... ...",
			GENERIC = "... ... ...",
		},
		LITTLE_WALRUS = "... ... ...",
		LIVINGLOG = "... ... ...",
		LOCKEDWES = "... ... ...",
		LOG =
		{
			BURNING = "... ... ...",
			GENERIC = "... ... ...",
		},
		LUREPLANT = "... ... ...",
		LUREPLANTBULB = "... ... ...",
		MALE_PUPPET = "... ... ...",
		MANDRAKE =
		{
			DEAD = "... ... ...",
			GENERIC = "... ... ...",
			PICKED = "... ... ...",
		},
		MANDRAKESOUP = "... ... ...",
		MANDRAKE_COOKED = "... ... ...",
		MARBLE = "... ... ...",
		MARBLEPILLAR = "... ... ...",
		MARBLETREE = "... ... ...",
		MARSH_BUSH =
		{
			BURNING = "... ... ...",
			GENERIC = "... ... ...",
			PICKED = "... ... ...",
		},
		MARSH_PLANT = "... ... ...",
		MARSH_TREE =
		{
			BURNING = "... ... ...",
			BURNT = "... ... ...",
			CHOPPED = "... ... ...",
			GENERIC = "... ... ...",
		},
		MAXWELL = "... ... ...",
		MAXWELLHEAD = "... ... ...",
		MAXWELLLIGHT = "... ... ...",
		MAXWELLLOCK = "... ... ...",
		MAXWELLTHRONE = "... ... ...",
		MEAT = "... ... ...",
		MEATBALLS = "... ... ...",
		MEATRACK =
		{
			DONE = "... ... ...",
			DRYING = "... ... ...",
			GENERIC = "... ... ...",
		},
		MEAT_DRIED = "... ... ...",
		MERM = "... ... ...!",
		MERMHEAD = "... ... ...",
		MERMHOUSE = "... ... ...",
		MINERHAT = "... ... ...",
		MONKEY = "... ... ...",
		MONKEYBARREL = "... ... ...",
		MONSTERLASAGNA = "... ... ...",
		MONSTERMEAT = "... ... ...",
		MONSTERMEAT_DRIED = "... ... ...",
		MOSQUITO =
		{
			GENERIC = "... ... ...",
			HELD = "... ... ...",
		},
		MOSQUITOSACK = "... ... ...",
		MOUND =
		{
			DUG = "... ... ...",
			GENERIC = "... ... ...",
		},
		NIGHTLIGHT = "... ... ...",
		NIGHTMAREFUEL = "... ... ...",
		NIGHTSWORD = "... ... ...",
		NITRE = "... ... ...",
		ONEMANBAND = "... ... ...",
		PANDORASCHEST = "... ... ...",
		PANFLUTE = "... ... ...",
		PAPYRUS = "... ... ...",
		PENGUIN = "... ... ...",
		PERD = "... ... ...",
		PEROGIES = "... ... ...",
		PETALS = "... ... ...",
		PETALS_EVIL = "... ... ...",
		PHLEGM = "... ... ....",
		PICKAXE = "... ... ...",
		PIGGYBACK = "... ... ...",
		PIGHEAD = "... ... ...",
		PIGHOUSE =
		{
			FULL = "... ... ...",
			GENERIC = "... ... ...",
			LIGHTSOUT = "... ... ...",
		},
		PIGKING = "... ... ...",
		PIGMAN =
		{
			DEAD = "... ... ...",
			FOLLOWER = "... ... ...",
			GENERIC = "... ... ...",
			GUARD = "... ... ...",
			WEREPIG = "... ... ...",
		},
		PIGSKIN = "... ... ...",
		PIGTENT = "... ... ...",
		PIGTORCH = "... ... ...",
		PINECONE = 
		{
		    GENERIC = "... ... ...",
		    PLANTED = "... ... ...",
		},
		PITCHFORK = "... ... ...",
		PLANTMEAT = "... ... ...",
		PLANTMEAT_COOKED = "... ... ...",
		PLANT_NORMAL =
		{
			GENERIC = "... ... ...",
			GROWING = "... ... ...",
			READY = "... ... ....",
		},
		POMEGRANATE = "... ... ...",
		POMEGRANATE_COOKED = "... ... ...",
		POMEGRANATE_SEEDS = "... ... ...",
		POND = "... ... ...",
		POOP = "... ... ...",
		PUMPKIN = "... ... ...",
		PUMPKINCOOKIE = "... ... ...",
		PUMPKIN_COOKED = "... ... ...",
		PUMPKIN_LANTERN = "... ... ...",
		PUMPKIN_SEEDS = "... ... ...",
		PURPLEAMULET = "... ... ...",
		PURPLEGEM = "... ... ...",
		RABBIT =
		{
			GENERIC = "... ... ...",
			HELD = "... ... ...",
		},
		RABBITHOLE = "... ... ...",
		RAINOMETER = "... ... ...",
		RATATOUILLE = "... ... ...",
		RAZOR = "... ... ...",
		REDGEM = "... ... ...",
		RED_CAP = "... ... ...",
		RED_CAP_COOKED = "... ... ...",
		RED_MUSHROOM =
		{
			GENERIC = "... ... ...",
			INGROUND = "... ... ...",
			PICKED = "... ... ...",
		},
		REEDS =
		{
			BURNING = "... ... ...",
			GENERIC = "... ... ...",
			PICKED = "... ... ...",
		},
        RELIC = 
        {
            GENERIC = "... ... ...",
            BROKEN = "... ... ...",
        },
        RUINS_RUBBLE = "... ... ...",
        RUBBLE = "... ... ...",
		RESEARCHLAB = "... ... ...",
		RESEARCHLAB2 = "... ... ...",
		RESEARCHLAB3 = "... ... ...",
		RESEARCHLAB4 = "... ... ...",
		RESURRECTIONSTATUE = "... ... ...!",
		RESURRECTIONSTONE = "... ... ...",
		ROBIN =
		{
			GENERIC = "... ... ...",
			HELD = "... ... ...",
		},
		ROBIN_WINTER =
		{
			GENERIC = "... ... ...",
			HELD = "... ... ...",
		},
		ROBOT_PUPPET = "... ... ...",
		ROCK_LIGHT =
		{
			GENERIC = "... ... ...",
			OUT = "... ... ...",
			LOW = "... ... ...",
			NORMAL = "... ... ...",
		},
		ROCK = "... ... ....",
		ROCKS = "... ... ...",
        ROOK = "... ... ...",
		ROPE = "... ... ...",
		ROTTENEGG = "... ... ...",
		SANITYROCK =
		{
			ACTIVE = "... ... ...",
			INACTIVE = "... ... ...",
		},
		SAPLING =
		{
			BURNING = "... ... ...",
			GENERIC = "... ... ...",
			PICKED = "... ... ...",
		},
		SEEDS = "... ... ...",
		SEEDS_COOKED = "... ... ...",
		SEWING_KIT = "... ... ...",
		SHOVEL = "... ... ...",
		SILK = "... ... ...",
		SKELETON = "... ... ...",
		SKULLCHEST = "... ... ...",
		SMALLBIRD =
		{
			GENERIC = "... ... ...",
			HUNGRY = "... ... ...",
			STARVING = "... ... ...",
		},
		SMALLMEAT = "... ... ...",
		SMALLMEAT_DRIED = "... ... ...",
		SPAT = "... ... ...",
		SPEAR = "... ... ...",
		SPIDER =
		{
			DEAD = "... ... ...",
			GENERIC = "... ... ...",
			SLEEPING = "... ... ...",
		},
		SPIDERDEN = "... ... ...",
		SPIDEREGGSACK = "... ... ...",
		SPIDERGLAND = "... ... ...",
		SPIDERHAT = "... ... ...",
		SPIDERQUEEN = "... ... ...",
		SPIDER_WARRIOR =
		{
			DEAD = "... ... ...",
			GENERIC = "... ... ...",
			SLEEPING = "... ... ...",
		},
		SPOILED_FOOD = "... ... ...",
		STATUEHARP = "... ... ...",
		STATUEMAXWELL = "... ... ...",
		STEELWOOL = "... ... ...",
		STINGER = "... ... ...",
		STRAWHAT = "... ... ...",
		STUFFEDEGGPLANT = "... ... ...",
		SUNKBOAT = "... ... ...",
		SWEATERVEST = "... ... ...",
		TAFFY = "... ... ...",
		TALLBIRD = "... ... ...",
		TALLBIRDEGG = "... ... ...",
		TALLBIRDEGG_COOKED = "... ... ...",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "... ... ...",
			GENERIC = "... ... ...",
			HOT = "... ... ...",
			LONG = "... ... ...",
			SHORT = "... ... ...",
		},
		TALLBIRDNEST =
		{
			GENERIC = "... ... ...",
			PICKED = "... ... ...",
		},
		TEENBIRD =
		{
			GENERIC = "... ... ...",
			HUNGRY = "... ... ...",
			STARVING = "... ... ...",
		},
		TELEBASE =
		{
			VALID = "... ... ...",
			GEMS = "... ... ...",
		},
		GEMSOCKET = 
		{
			VALID = "... ... ...",
			GEMS = "... ... ...",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "... ... ...",
			GENERIC = "... ... ...",
			LOCKED = "... ... ...",
			PARTIAL = "... ... ...",
		},
		TELEPORTATO_BOX = "... ... ...",
		TELEPORTATO_CRANK = "... ... ...",
		TELEPORTATO_POTATO = "... ... ...",
		TELEPORTATO_RING = "... ... ...",
		TELESTAFF = "... ... ...",
		TENT = "... ... ...",
		TENTACLE = "... ... ...",
		TENTACLESPIKE = "... ... ...",
		TENTACLESPOTS = "... ... ...",
		TENTACLE_PILLAR = "... ... ...",
		TENTACLE_PILLAR_ARM = "... ... ...",
		TENTACLE_GARDEN = "... ... ...",
		TOPHAT = "... ... ...",
		TORCH = "... ... ...",
		TRAP = "... ... ...",
		TRAP_TEETH = "... ... ...",
		TRAP_TEETH_MAXWELL = "... ... ...",
		TREASURECHEST = "... ... ...",
		TREASURECHEST_TRAP = "... ... ...",
		TREECLUMP = "... ... ...",
		TRINKET_1 = "... ... ...",
		TRINKET_10 = "... ... ...",
		TRINKET_11 = "... ... ...",
		TRINKET_12 = "... ... ...",
		TRINKET_13 = "... ... ...",
		TRINKET_2 = "... ... ...",
		TRINKET_3 = "... ... ...",
		TRINKET_4 = "... ... ...",
		TRINKET_5 = "... ... ...",
		TRINKET_6 = "... ... ...",
		TRINKET_7 = "... ... ...",
		TRINKET_8 = "... ... ...",
		TRINKET_9 = "... ... ...",
		TRUNKVEST_SUMMER = "... ... ...",
		TRUNKVEST_WINTER = "... ... ...",
		TRUNK_COOKED = "... ... ...",
		TRUNK_SUMMER = "... ... ...",
		TRUNK_WINTER = "... ... ...",
		TURF_CARPETFLOOR = "... ... ...",
		TURF_CHECKERFLOOR = "... ... ...",
		TURF_DIRT = "... ... ...",
		TURF_FOREST = "... ... ...",
		TURF_GRASS = "... ... ...",
		TURF_MARSH = "... ... ...",
		TURF_ROAD = "... ... ...",
		TURF_ROCKY = "... ... ...",
		TURF_SAVANNA = "... ... ...",
		TURF_WOODFLOOR = "... ... ...",
		TURKEYDINNER = "... ... ...",
		TWIGS = "... ... ...",
		UMBRELLA = "... ... ...",
		UNIMPLEMENTED = "... ... ...",
		WAFFLES = "... ... ...",
		WALL_HAY = "... ... ...",
		WALL_HAY_ITEM = "... ... ...",
		WALL_STONE = "... ... ...",
		WALL_STONE_ITEM = "... ... ...",
		WALL_RUINS = "... ... ...",
		WALL_RUINS_ITEM = "... ... ...",
		WALL_WOOD = "... ... ...",
		WALL_WOOD_ITEM = "... ... ...",
		WALL_MOONROCK = "... ... ...",
		WALL_MOONROCK_ITEM = "... ... ...",
		WALRUS = "... ... ...",
		WALRUSHAT = "... ... ...",
		WALRUS_CAMP =
		{
			EMPTY = "... ... ...",
			GENERIC = "... ... ...",
		},
		WALRUS_TUSK = "... ... ...",
		WARG = "... ... ...",
		WASPHIVE = "... ... ...",
		WETGOOP = "... ... ...",
		WINTERHAT = "... ... ...",
		WINTEROMETER = "... ... ...",
		WORMHOLE =
		{
			GENERIC = "... ... ...",
			OPEN = "... ... ...",
		},
		WORMHOLE_LIMITED = "... ... ...",
		ACCOMPLISHMENT_SHRINE = "... ... ...",        
		LIVINGTREE = "... ... ...",
		ICESTAFF = "... ... ...",
		REVIVER = "... ... ...",
		LIFEINJECTOR = "... ... ...",
		SKELETON_PLAYER =
		{
			MALE = "... ... ...",
			FEMALE = "... ... ...",
			ROBOT = "... ... ...",
		},
		HUMANMEAT = "... ... ...",
		HUMANMEAT_COOKED = "... ... ...",
		HUMANMEAT_DRIED = "... ... ...",
		MOONROCKNUGGET = "... ... ...",
	},
	DESCRIBE_GENERIC = "... ... ...",
	DESCRIBE_TOODARK = "... ... ...",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "... ... ...",
	},
}
